// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcubeguzugyxgijsggmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjdWJlZ3V6dWd5eGdpanNnZ21vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMzYyMzMsImV4cCI6MjA2NzkxMjIzM30.X1akPiLi0z6yzxxmDXK2ZSQpMTVJOsBdYHaEq0SF8ZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});