// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymygasvnpvhihlyydsra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlteWdhc3ZucHZoaWhseXlkc3JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NzIyMzMsImV4cCI6MjA2ODU0ODIzM30.KAHzA0Vzx6k7VeDuZVVL_0m0YxArjdeoC9KyY9FBPtQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});